import os
import json
import logging
from typing import Dict, Any, List, Optional
from fpdf import FPDF

logger = logging.getLogger("report_service")


def _latin1_safe(text: Any) -> str:
    """
    Sanitizes strings for FPDF built-in Helvetica font by converting non-Latin1
    characters (em-dashes, smart quotes, currency symbols) to ASCII equivalents.
    """
    if text is None:
        return ""
    s = str(text)
    s = (
        s.replace("—", "-")
        .replace("–", "-")
        .replace("“", '"')
        .replace("”", '"')
        .replace("’", "'")
        .replace("₹", "Rs.")
        .replace("™", "")
        .replace("®", "")
    )
    return s.encode("latin-1", "replace").decode("latin-1")


class PDFReport(FPDF):

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(10, 10, 10)
        self.cell(0, 10, _latin1_safe("BRAND PROTECTION CASE REPORT"), ln=False)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(115, 115, 115)
        self.cell(0, 10, _latin1_safe("CONFIDENTIAL — KEIKAI INTELLIGENCE"), align="R", ln=True)
        self.set_draw_color(229, 229, 229)
        self.set_line_width(0.5)
        self.line(10, 22, 200, 22)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(115, 115, 115)
        self.cell(0, 10, _latin1_safe(f"Page {self.page_no()} | Generated by KEIKAI Threat Intelligence Engine"), align="C")


def calculate_dynamic_composite_risk(
    evidence_domains: List[Dict[str, Any]],
    evidence_logos: List[Dict[str, Any]],
    evidence_visual_phishing: List[Dict[str, Any]],
    evidence_listings: List[Dict[str, Any]] = None,
    evidence_social_profiles: List[Dict[str, Any]] = None,
    manual_notes: Optional[str] = None,
    intent_discount: float = 0.0
) -> Dict[str, Any]:
    """
    Refactored Dynamic Weighted Composite Risk Score Formula.
    Scales weights dynamically based on present evidence surfaces.
    """
    evidence_listings = evidence_listings or []
    evidence_social_profiles = evidence_social_profiles or []

    present_sources = {
        "domain": len(evidence_domains) > 0,
        "logo": len(evidence_logos) > 0,
        "phish": len(evidence_visual_phishing) > 0,
        "listing": len(evidence_listings) > 0,
        "social": len(evidence_social_profiles) > 0,
        "notes": bool(manual_notes and manual_notes.strip())
    }

    base_weights = {
        "domain": 25.0,
        "logo": 25.0,
        "phish": 20.0,
        "listing": 15.0,
        "social": 15.0,
        "notes": 10.0
    }

    active_weight_sum = sum(base_weights[k] for k, present in present_sources.items() if present)

    if active_weight_sum <= 0:
        return {
            "composite_risk_score": 0.0,
            "score_factors": {},
            "dynamic_weights": {},
            "present_sources": present_sources,
            "verdict": "Low Risk / Clean"
        }

    dynamic_weights = {
        k: round((base_weights[k] / active_weight_sum) * 100.0, 1) if present else 0.0
        for k, present in present_sources.items()
    }

    # Factor Scores
    domain_score = max([float(d.get("riskScore", 75.0)) for d in evidence_domains], default=0.0) if present_sources["domain"] else 0.0
    logo_score = max([float(l.get("combined_similarity_percentage", 80.0)) for l in evidence_logos], default=0.0) if present_sources["logo"] else 0.0
    phish_score = max([float(p.get("confidence", 90.0)) for p in evidence_visual_phishing], default=0.0) if present_sources["phish"] else 0.0
    listing_score = max([float(m.get("risk_rating", 85.0)) for m in evidence_listings], default=0.0) if present_sources["listing"] else 0.0
    social_score = max([float(s.get("risk_rating", 85.0)) for s in evidence_social_profiles], default=0.0) if present_sources["social"] else 0.0
    notes_score = 90.0 if present_sources["notes"] else 0.0

    domain_factor = (domain_score * dynamic_weights["domain"]) / 100.0
    logo_factor = (logo_score * dynamic_weights["logo"]) / 100.0
    phish_factor = (phish_score * dynamic_weights["phish"]) / 100.0
    listing_factor = (listing_score * dynamic_weights["listing"]) / 100.0
    social_factor = (social_score * dynamic_weights["social"]) / 100.0
    notes_factor = (notes_score * dynamic_weights["notes"]) / 100.0

    raw_composite = domain_factor + logo_factor + phish_factor + listing_factor + social_factor + notes_factor
    final_composite = max(0.0, min(100.0, round(raw_composite - intent_discount, 1)))

    if final_composite >= 75.0:
        verdict = "Critical / High Risk Brand Threat"
    elif final_composite >= 45.0:
        verdict = "Medium Risk / Suspicious Activity"
    else:
        verdict = "Low Risk / Authorized Activity"

    return {
        "composite_risk_score": final_composite,
        "verdict": verdict,
        "dynamic_weights": dynamic_weights,
        "score_factors": {
            "domain_factor": round(domain_factor, 1),
            "logo_factor": round(logo_factor, 1),
            "phish_factor": round(phish_factor, 1),
            "listing_factor": round(listing_factor, 1),
            "social_factor": round(social_factor, 1),
            "notes_factor": round(notes_factor, 1),
            "intent_discount": round(intent_discount, 1)
        },
        "present_sources": present_sources
    }


def generate_pdf_report(case_data: Dict[str, Any]) -> bytes:
    """
    Generates a downloadable PDF case report compiling flagged evidence across all 5 surfaces.
    Sanitizes strings with _latin1_safe() for FPDF compatibility.
    """
    pdf = PDFReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    case_id = _latin1_safe(case_data.get("case_id", "CASE-REPORT-001"))
    timestamp = _latin1_safe(case_data.get("timestamp", "2026-08-22 09:00:00 UTC"))
    brand_name = _latin1_safe(case_data.get("brand_name", "Target Brand"))
    score = float(case_data.get("composite_risk_score", 85.5))
    manual_notes = _latin1_safe(case_data.get("manual_notes", ""))

    # Executive Overview
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(10, 10, 10)
    pdf.cell(40, 6, "Case ID:", border=0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(60, 6, case_id, border=0)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, "Target Brand:", border=0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(50, 6, brand_name, border=0, ln=True)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, "Generated Date:", border=0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(60, 6, timestamp, border=0)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, "Composite Risk:", border=0)

    if score >= 75:
        pdf.set_text_color(231, 0, 11)
    elif score >= 45:
        pdf.set_text_color(217, 119, 6)
    else:
        pdf.set_text_color(16, 185, 129)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(50, 6, f"{score:.1f}% / 100", border=0, ln=True)
    pdf.set_text_color(10, 10, 10)
    pdf.ln(4)

    # Risk Score Breakdown Table
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(10, 10, 10)
    pdf.cell(0, 8, _latin1_safe("1. Explainable Risk Score Breakdown"), ln=True)

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(30, 41, 59)
    pdf.cell(60, 6, "Evidence Layer", border=1, fill=True)
    pdf.cell(45, 6, "Dynamic Weight", border=1, fill=True)
    pdf.cell(45, 6, "Calculated Contribution", border=1, fill=True)
    pdf.cell(40, 6, "Status", border=1, fill=True, ln=True)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(51, 65, 85)

    breakdown = case_data.get("score_breakdown", {})
    weights = breakdown.get("weights", {})
    score_factors = breakdown

    domain_factor = score_factors.get("domain_factor", 0.0)
    logo_factor = score_factors.get("logo_factor", 0.0)
    phish_factor = score_factors.get("phish_factor", 0.0)
    listing_factor = score_factors.get("listing_factor", 0.0)
    social_factor = score_factors.get("social_factor", 0.0)
    notes_factor = score_factors.get("notes_factor", 0.0)
    intent_discount = score_factors.get("intent_discount", 0.0)

    domain_items = case_data.get("flagged_domains", [])
    if domain_items or weights.get("domain", 0) > 0:
        pdf.cell(60, 6, "Domain Typo-Squatting Risk", border=1)
        pdf.cell(45, 6, f"{weights.get('domain', 25.0):.1f}%", border=1)
        pdf.cell(45, 6, f"{domain_factor:.1f} pts", border=1)
        pdf.cell(40, 6, f"{len(domain_items)} domain(s)", border=1, ln=True)

    logo_items = case_data.get("flagged_logos", [])
    if logo_items or weights.get("logo", 0) > 0:
        pdf.cell(60, 6, "Logo Hash Likeness", border=1)
        pdf.cell(45, 6, f"{weights.get('logo', 25.0):.1f}%", border=1)
        pdf.cell(45, 6, f"{logo_factor:.1f} pts", border=1)
        pdf.cell(40, 6, f"{len(logo_items)} logo match(es)", border=1, ln=True)

    phish_items = case_data.get("visual_phishing", [])
    if phish_items or weights.get("phish", 0) > 0:
        pdf.cell(60, 6, "Visual Phishing Detection", border=1)
        pdf.cell(45, 6, f"{weights.get('phish', 20.0):.1f}%", border=1)
        pdf.cell(45, 6, f"{phish_factor:.1f} pts", border=1)
        pdf.cell(40, 6, f"{len(phish_items)} visual check(s)", border=1, ln=True)

    listing_items = case_data.get("flagged_listings", [])
    if listing_items or weights.get("listing", 0) > 0:
        pdf.cell(60, 6, "Marketplace Listing Risk", border=1)
        pdf.cell(45, 6, f"{weights.get('listing', 15.0):.1f}%", border=1)
        pdf.cell(45, 6, f"{listing_factor:.1f} pts", border=1)
        pdf.cell(40, 6, f"{len(listing_items)} listing(s)", border=1, ln=True)

    social_items = case_data.get("flagged_social_profiles", [])
    if social_items or weights.get("social", 0) > 0:
        pdf.cell(60, 6, "Social Impersonation Risk", border=1)
        pdf.cell(45, 6, f"{weights.get('social', 15.0):.1f}%", border=1)
        pdf.cell(45, 6, f"{social_factor:.1f} pts", border=1)
        pdf.cell(40, 6, f"{len(social_items)} profile(s)", border=1, ln=True)

    if manual_notes or weights.get("notes", 0) > 0:
        pdf.cell(60, 6, "Investigator Severity Assessment", border=1)
        pdf.cell(45, 6, f"{weights.get('notes', 10.0):.1f}%", border=1)
        pdf.cell(45, 6, f"{notes_factor:.1f} pts", border=1)
        pdf.cell(40, 6, "Manual Rationale", border=1, ln=True)

    pdf.ln(6)

    # Investigator Notes
    if manual_notes:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(10, 10, 10)
        pdf.cell(0, 8, _latin1_safe("2. Investigator Notes & Observations"), ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(51, 65, 85)
        pdf.multi_cell(190, 6, manual_notes, border=1)
        pdf.ln(6)

    # Flagged Domain Evidence
    if domain_items:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(10, 10, 10)
        pdf.cell(0, 8, _latin1_safe(f"3. Flagged Domain Evidence ({len(domain_items)} item(s))"), ln=True)

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(50, 6, "Permutation Domain", border=1, fill=True)
        pdf.cell(30, 6, "Fuzzer Type", border=1, fill=True)
        pdf.cell(20, 6, "Reg.", border=1, fill=True)
        pdf.cell(50, 6, "Intent Classification", border=1, fill=True)
        pdf.cell(40, 6, "IP Address", border=1, fill=True, ln=True)

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(51, 65, 85)
        for dom in domain_items[:15]:
            domain_name = _latin1_safe(dom.get("domain", ""))
            fuzzer = _latin1_safe(dom.get("fuzzer", "N/A"))
            registered = "YES" if dom.get("dns_a") or dom.get("registered") else "NO"
            ip = ", ".join(dom.get("dns_a", [])) if isinstance(dom.get("dns_a"), list) else _latin1_safe(dom.get("dns_a", "N/A"))
            intent = _latin1_safe(dom.get("intentLabel") or dom.get("intent_label") or "Unclassified")

            pdf.cell(50, 6, domain_name[:28], border=1)
            pdf.cell(30, 6, fuzzer[:18], border=1)
            pdf.cell(20, 6, registered, border=1)
            pdf.cell(50, 6, intent[:28], border=1)
            pdf.cell(40, 6, ip[:20], border=1, ln=True)
        pdf.ln(6)

    # Section 8: Linked Infrastructure & Offender Infrastructure Clusters
    try:
        from services.infrastructure_service import get_offender_clusters
        cluster_data = get_offender_clusters()
        clusters = cluster_data.get("clusters", [])
        if clusters:
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(10, 10, 10)
            pdf.cell(0, 8, _latin1_safe(f"8. Linked Infrastructure & Offender Threat Clusters ({len(clusters)} cluster(s))"), ln=True)

            for cl in clusters[:5]:
                cid = _latin1_safe(cl.get("cluster_id", "CLUSTER-001"))
                conf = _latin1_safe(cl.get("confidence", "Medium"))
                score_val = cl.get("confidence_score", 70)
                summary_text = _latin1_safe(cl.get("plain_language_summary", ""))

                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(255, 255, 255)
                pdf.cell(50, 6, _latin1_safe(f"Threat Cluster: {cid}"), border=1, fill=True)
                pdf.cell(60, 6, _latin1_safe(f"Confidence: {conf} ({score_val}%)"), border=1, fill=True)
                pdf.cell(80, 6, _latin1_safe(f"Asset Count: {cl.get('asset_count', 0)} properties"), border=1, fill=True, ln=True)

                if summary_text:
                    pdf.set_font("Helvetica", "I", 8)
                    pdf.set_text_color(51, 65, 85)
                    pdf.multi_cell(190, 5, _latin1_safe(f"Finding Summary: {summary_text}"), border=1)

                pdf.ln(2)
            pdf.ln(4)
    except Exception as cl_err:
        logger.warning("Failed to render cluster section in PDF report: %s", cl_err)

    # Section 9: Appendix — Investigation Audit Trail & Technical Rationale
    try:
        from database import fetch_case_timeline
        events = fetch_case_timeline(case_id)
        if events:
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(10, 10, 10)
            pdf.cell(0, 8, _latin1_safe("9. Appendix: Investigation Audit Trail & Activity Log"), ln=True)

            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(45, 6, "Timestamp (UTC)", border=1, fill=True)
            pdf.cell(35, 6, "Event Type", border=1, fill=True)
            pdf.cell(110, 6, "Description & Audit Rationale", border=1, fill=True, ln=True)

            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(51, 65, 85)
            for ev in events[:20]:
                ts = _latin1_safe(ev.get("created_at", ""))
                etype = _latin1_safe(ev.get("event_type", "event"))
                desc = _latin1_safe(ev.get("description", ""))

                pdf.cell(45, 6, ts[:19], border=1)
                pdf.cell(35, 6, etype[:18], border=1)
                pdf.cell(110, 6, desc[:65], border=1, ln=True)
    except Exception:
        pass

    return bytes(pdf.output())
